apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-test
  template:
    metadata:
      labels:
        app: deploy-test
    spec:
      containers:
        - name: deploy-test
          image: 10.0.0.211:5000/deploy_test:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: deploy-test-service
  namespace: default
spec:
  selector:
    app: deploy-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
